In [1]:
import pandas as pd
products = [{'Name' : 'เมาส์','Category': 'อุปกรณ์คอม', 'Price': 250}
            ,{'Name' : 'คีบอร์ด', 'Category' : 'อุปกรณ์คอม', 'Price': 300}
            ,{'Name' : 'จอคอมพิวเตอร์', 'Category' : 'อุปกรณ์คอม', 'Price': 5000}]

In [2]:
df = pd.DataFrame(products)

In [3]:
df

            Name    Category  Price
0          เมาส์  อุปกรณ์คอม    250
1        คีบอร์ด  อุปกรณ์คอม    300
2  จอคอมพิวเตอร์  อุปกรณ์คอม   5000

In [4]:
df.set_index('Name', inplace=True)

In [5]:
df

                 Category  Price
Name
เมาส์          อุปกรณ์คอม    250
คีบอร์ด        อุปกรณ์คอม    300
จอคอมพิวเตอร์  อุปกรณ์คอม   5000