In [1]:
import pandas as pd
datas = [['เมาส์','IT','1000'],['โยโย่','ของเล่น','500'],['กระทะไฟฟ้า','ห้องครัว','3000'],['คีย์บอร์ด','IT','1500'],['จาน','ห้องครัว','200']]
df = pd.DataFrame(datas, columns=['ชื่อสินค้า', 'หมวดหมู่', 'ราคา'])

In [2]:
df

   ชื่อสินค้า  หมวดหมู่  ราคา
0       เมาส์        IT  1000
1       โยโย่   ของเล่น   500
2  กระทะไฟฟ้า  ห้องครัว  3000
3   คีย์บอร์ด        IT  1500
4         จาน  ห้องครัว   200

In [3]:
datas2 = [['เมาส์','IT','1000'],['ตุ๊กตา','ของเล่น','500'],['กระทะไฟฟ้า','ห้องครัว','3000'],['จอภาพ','IT','1500'],['ช้อน','ห้องครัว','200']]

In [4]:
col = ['ชื่อสินค้า', 'หมวดหมู่', 'ราคา']
df2 = pd.DataFrame(datas2, columns=col)

In [5]:
df2

   ชื่อสินค้า  หมวดหมู่  ราคา
0       เมาส์        IT  1000
1      ตุ๊กตา   ของเล่น   500
2  กระทะไฟฟ้า  ห้องครัว  3000
3       จอภาพ        IT  1500
4        ช้อน  ห้องครัว   200